### ISSUE TITLE
无法正常使用缩放功能

### ISSUE THREAD

**Issue by LrbsX** [IAFEnvoy/TitleScreenMobs-Arch#4]
mod版本：TitleScreenMobs-0.2-1.21-fabric.jar
fabric版本：0.16.7，api-0.102.0
如图所示，使用配置文件中的缩放功能进行缩放会出现模型直接被截断的现象。
这里是缩放1.5倍的效果
![image](https://github.com/user-attachments/assets/c9f0967c-bf2e-47a6-aff2-66d16f9a8aa0)

**Comment by IAFEnvoy** [comment]
更新，0.2.1修了
