### ISSUE TITLE
1.20.1 NeoForge Crashes

### ISSUE THREAD

**Issue by Apollonu** [IAFEnvoy/TitleScreenMobs-Arch#5]
This Mod is incompatible with Forgery and Retro Damage Indicators on launch. It causes the game to crash, maybe as to how you are rendering the player.

**Comment by IAFEnvoy** [comment]
Please provide a crash log

**Comment by Apollonu** [comment]
[Forgery Crash.txt](https://github.com/user-attachments/files/17966471/Forgery.Crash.txt)
[Retro Damage Indicators Crash.txt](https://github.com/user-attachments/files/17966472/Retro.Damage.Indicators.Crash.txt)

**Comment by Apollonu** [comment]
Without either of these it works, besides the cape looking weird but thats not important. (no gravity + position)

**Comment by IAFEnvoy** [comment]
For Forgery, try to disable `use_player_list_name_in_tag` first. I will check this issue later.

For Retro Damage Indicators, i don't think it is my problem.

**Comment by Apollonu** [comment]
Disabling the setting in Forgery allowed them to load together, I will open an issue on Retro Damage Indicators, but I don't know if it will actually be fixed.

**Comment by IAFEnvoy** [comment]
Retro Damage Indicators misses a null check which cause crash

**Comment by Apollonu** [comment]
I got it to work lmao... I was on 1.0.0 due to incompatiblities with ImmediatelyFast but I can get that issue to disappear now (I think)..1.0.0 is incompatible but 1.0.1 works (of RetroDamageIndicators)
